# Generated by Django 5.0.1 on 2024-01-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='has_company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='resume',
            new_name='has_resume',
        ),
    ]
